version: '3.9'

networks:
  mynetwork:
    driver: bridge

services:
  cassandra:
    image: bitnami/cassandra:latest
    container_name: cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_CLUSTER_NAME=cassandra-dbms
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_LISTEN_ADDRESS=0.0.0.0
      - CASSANDRA_START_RPC=true
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces;'"]
      timeout: 120s
      retries: 3 
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - mynetwork  
  app:
    container_name: dbms_app
    build: 
      context: .
      dockerfile: DockerFile
    ports:
      - "5000:5000"
    depends_on:
      - cassandra
      - mysql
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONDONTWRITEBYTECODE=1
    networks:
      - mynetwork
  mysql:
    container_name: db_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: myuser
      MYSQL_DATABASE: mydb
      MYSQL_PASSWORD: abcd
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=dbms-topic:1:1
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    volumes:
      - ./zookeeper_data:/data
volumes:
  mysql_data:
    driver: local
